# Forming Cosine Similarity Groups

Cosine Similarity groups are found to form as a base for classification algorithms such as logistic regression, random forrests and XGboost.

## Loading Data

In [2]:
import pandas as pd
df = pd.read_csv("data/spotify_data.csv", index_col= None)
df.head()

,track_id,artists,album_name,track_name,popularity,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,duration_s
0,0000vdREvCVMxbQTkS888c,['Rill'],['Lolly'],['Lolly'],44.0,1.0,0.910,0.374,8.0,-9.844,0.0,0.1990,0.075700,0.00301,0.1540,0.432,104.042,4.0,['german'],160.725
1,000CC8EParg64OmTxVnZ0p,['Glee Cast'],['Glee Love Songs'],"[""It's All Coming Back To Me Now (Glee Cast Ve...",47.0,0.0,0.269,0.516,0.0,-7.361,1.0,0.0366,0.406000,0.00000,0.1170,0.341,178.174,4.0,['club'],322.933
2,000Iz0K615UepwSJ5z2RE5,['Paul Kalkbrenner;Pig&Dan'],['X'],['Böxig Leise - Pig & Dan Remix'],22.0,0.0,0.686,0.560,5.0,-13.264,0.0,0.0462,0.001140,0.18100,0.1110,0.108,119.997,4.0,['minimal-techno'],515.360
3,000RDCYioLteXcutOjeweY,['Jordan Sandhu'],['Teeje Week'],['Teeje Week'],62.0,0.0,0.679,0.770,0.0,-3.537,1.0,0.1900,0.058300,0.00000,0.0825,0.839,161.721,4.0,['hip-hop'],190.203
4,000qpdoc97IMTBvF8gwcpy,['Paul Kalkbrenner'],['Zeit'],['Tief'],19.0,0.0,0.519,0.431,6.0,-13.606,0.0,0.0291,0.000964,0.72000,0.0916,0.234,129.971,4.0,['minimal-techno'],331.240

In [3]:
data = df.drop(columns = ["track_name"])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89740 entries, 0 to 89739
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          89740 non-null  object
 1   artists           89740 non-null  object
 2   album_name        89740 non-null  object
 3   popularity        89740 non-null  float64
 4   explicit          89740 non-null  float64
 5   danceability      89740 non-null  float64
 6   energy            89740 non-null  float64
 7   key               89740 non-null  float64
 8   loudness          89740 non-null  float64
 9   mode              89740 non-null  float64
 10  speechiness       89740 non-null  float64
 11  acousticness      89740 non-null  float64
 12  instrumentalness  89740 non-null  float64
 13  liveness          89740 non-null  float64
 14  valence           89740 non-null  float64
 15  tempo             89740 non-null  float64
 16  time_signature    89740 non-null  float64
 17  track_genre       89740 non-null  object
 18  duration_s        89740 non-null  float64
dtypes: float64(15), object(4)
memory usage: 13.0+ MB

### Cosine Similarity

In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [5]:

## Getting numerical features for cosine similarity 
features = data.iloc[:, 3:].drop(columns = "track_genre")

features.head()

,popularity,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_s
0,44.0,1.0,0.910,0.374,8.0,-9.844,0.0,0.1990,0.075700,0.00301,0.1540,0.432,104.042,4.0,160.725
1,47.0,0.0,0.269,0.516,0.0,-7.361,1.0,0.0366,0.406000,0.00000,0.1170,0.341,178.174,4.0,322.933
2,22.0,0.0,0.686,0.560,5.0,-13.264,0.0,0.0462,0.001140,0.18100,0.1110,0.108,119.997,4.0,515.360
3,62.0,0.0,0.679,0.770,0.0,-3.537,1.0,0.1900,0.058300,0.00000,0.0825,0.839,161.721,4.0,190.203
4,19.0,0.0,0.519,0.431,6.0,-13.606,0.0,0.0291,0.000964,0.72000,0.0916,0.234,129.971,4.0,331.240

In [6]:
# making track_genre numerical 
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=True, handle_unknown="ignore")
genre_matrix = encoder.fit_transform(df[["track_genre"]])

genre_df = pd.DataFrame.sparse.from_spmatrix(
    genre_matrix,
    index=features.index,
    columns=encoder.get_feature_names_out(["track_genre"])
)

data_cosine = pd.concat([features, genre_df], axis=1)
data_cosine.head()

,popularity,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,track_genre_['spanish'],track_genre_['study'],track_genre_['swedish'],track_genre_['synth-pop'],track_genre_['tango'],track_genre_['techno'],track_genre_['trance'],track_genre_['trip-hop'],track_genre_['turkish'],track_genre_['world-music']
0,44.0,1.0,0.910,0.374,8.0,-9.844,0.0,0.1990,0.075700,0.00301,...,0,0,0,0,0,0,0,0,0,0
1,47.0,0.0,0.269,0.516,0.0,-7.361,1.0,0.0366,0.406000,0.00000,...,0,0,0,0,0,0,0,0,0,0
2,22.0,0.0,0.686,0.560,5.0,-13.264,0.0,0.0462,0.001140,0.18100,...,0,0,0,0,0,0,0,0,0,0
3,62.0,0.0,0.679,0.770,0.0,-3.537,1.0,0.1900,0.058300,0.00000,...,0,0,0,0,0,0,0,0,0,0
4,19.0,0.0,0.519,0.431,6.0,-13.606,0.0,0.0291,0.000964,0.72000,...,0,0,0,0,0,0,0,0,0,0

In [7]:
#scaling continous columns
from sklearn.preprocessing import StandardScaler

audio_cols = [
    "popularity", "danceability", "energy", "loudness", "speechiness", "acousticness", "instrumentalness", "liveness", "valence", "tempo", "duration_s"
]

scaler = StandardScaler()
data_cosine[audio_cols] = scaler.fit_transform(data_cosine[audio_cols])

data_cosine.head()

,popularity,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,track_genre_['spanish'],track_genre_['study'],track_genre_['swedish'],track_genre_['synth-pop'],track_genre_['tango'],track_genre_['techno'],track_genre_['trance'],track_genre_['trip-hop'],track_genre_['turkish'],track_genre_['world-music']
0,0.524826,1.0,1.968598,-1.015017,8.0,-0.257591,0.0,0.984821,-0.746589,-0.526190,...,0,0,0,0,0,0,0,0,0,0
1,0.670595,0.0,-1.659203,-0.461638,0.0,0.217944,1.0,-0.448832,0.229710,-0.535485,...,0,0,0,0,0,0,0,0,0,0
2,-0.544146,0.0,0.700848,-0.290168,5.0,-0.912576,0.0,-0.364084,-0.966973,0.023420,...,0,0,0,0,0,0,0,0,0,0
3,1.399439,0.0,0.661231,0.528211,0.0,0.950303,1.0,0.905370,-0.798020,-0.535485,...,0,0,0,0,0,0,0,0,0,0
4,-0.689915,0.0,-0.244304,-0.792886,6.0,-0.978075,0.0,-0.515041,-0.967493,1.687784,...,0,0,0,0,0,0,0,0,0,0

In [8]:
from sklearn.neighbors import NearestNeighbors
from scipy.sparse import csr_matrix

X = csr_matrix(data_cosine.values)

nn_model = NearestNeighbors(
    metric = "cosine", algorithm = 'brute'
    )

nn_model.fit(X)

NearestNeighbors(algorithm='brute', metric='cosine')

In [9]:

#distances, indices = nn_model.kneighbors(X, n_neighbors = 6) <-- takes way too long

sample_X = X[:1000]
distances, indices = nn_model.kneighbors(sample_X, n_neighbors = 6)

In [10]:
# batch_size = 200
# neighbours = 5 ##how many neighbours you want to the song, + 1 is added in the loop so the algorithm runs properly
# all_rows = []

# for start in range (0, X.shape[0], batch_size):
#     end = min(start + batch_size, X.shape[0])
#     print(f"Processing rows {start} to {end}")

#     distances, indices = nn_model.kneighbors(X[start:end], n_neighbors = neighbours + 1)
#     similarities = 1 - distances

#     for i in range (end - start):
#         seed_idx = start + i

#         for j in range(1, 6):  # skip itself
#             neighbour_idx = indices[i][j]
#             all_rows.append({
#                 "seed_track_id": df.iloc[seed_idx]["track_id"],
#                 "similar_track_id": df.iloc[neighbour_idx]["track_id"],
#                 "similarity": similarities[i][j]
#             })

# similarity_df = pd.DataFrame(all_rows)

The code output above too 4m 14.0s to process on a mac boook pro m1 32gb ram. It is very computationally heavy and should only be run when necessary. If testing is necessary, use sample block above. Refer to saved data for distances, indices and similarity scores.

In [11]:
#saving everything so I don't have to run the code above again (it took 4m 14.0s)
# np.save("numpy_files/distances.npy", distances)
# np.save("numpy_files/indices.npy", indices)
# similarity_df.to_csv("data/similarity_groups.csv", index = False)

In [12]:
similarity_scores = pd.read_csv("data/similarity_groups.csv")
similarity_scores.head()

            seed_track_id        similar_track_id  similarity
0  0000vdREvCVMxbQTkS888c  2DX4Lj4wXV3VK1F8yl0x54    0.982958
1  0000vdREvCVMxbQTkS888c  4bYH5445Bn2w9UiGM0NxQw    0.981924
2  0000vdREvCVMxbQTkS888c  5u7QargOKXO82nXcAU9s8L    0.980754
3  0000vdREvCVMxbQTkS888c  0wi1ky0zqwG8195E4omWui    0.977883
4  0000vdREvCVMxbQTkS888c  6wKKcAUaLYDy7bN1uFD0E5    0.977732

In [13]:
# create positive pairs

positive_pairs = similarity_scores.copy()
positive_pairs['target'] = 1
positive_pairs.head()

            seed_track_id        similar_track_id  similarity  target
0  0000vdREvCVMxbQTkS888c  2DX4Lj4wXV3VK1F8yl0x54    0.982958       1
1  0000vdREvCVMxbQTkS888c  4bYH5445Bn2w9UiGM0NxQw    0.981924       1
2  0000vdREvCVMxbQTkS888c  5u7QargOKXO82nXcAU9s8L    0.980754       1
3  0000vdREvCVMxbQTkS888c  0wi1ky0zqwG8195E4omWui    0.977883       1
4  0000vdREvCVMxbQTkS888c  6wKKcAUaLYDy7bN1uFD0E5    0.977732       1

In [14]:
# np.random.seed(42)

# all_tracks = data['track_id'].unique()
# negative_rows = []


# positive_map = (
#     positive_pairs.groupby("seed_track_id")["similar_track_id"]
#     .apply(set)
#     .to_dict()
# )

# for seed_id, pos_set in positive_map.items():
#     excluded = pos_set | {seed_id}

#     candidate_pool = np.array([tid for tid in all_tracks if tid not in excluded])

#     n_neg = len(pos_set)

#     if len(candidate_pool) < n_neg:
#         sampled_negatives = candidate_pool
    
#     else: 
#         sampled_negatives = np.random.choice(candidate_pool, size = n_neg, replace = False)
    
#     for neg_id in sampled_negatives:
#         negative_rows.append({
#             "seed_track_id": seed_id,
#             "similar_track_id": neg_id,
#             "target": 0
#         })

# neg_pairs = pd.DataFrame(negative_rows)

In [15]:
np.random.seed(42)

all_tracks = data["track_id"].unique()
negative_rows = []

positive_map = (
    positive_pairs.groupby("seed_track_id")["similar_track_id"]
    .apply(set)
    .to_dict()
)

for seed_id, pos_set in positive_map.items():
    excluded = pos_set | {seed_id}
    n_neg = len(pos_set)

    sampled = []
    sampled_set = set()

    while len(sampled) < n_neg:
        candidate = np.random.choice(all_tracks)
        if candidate not in excluded and candidate not in sampled_set:
            sampled.append(candidate)
            sampled_set.add(candidate)

    negative_rows.extend(
        {
            "seed_track_id": seed_id,
            "similar_track_id": neg_id,
            "target": 0
        }
        for neg_id in sampled
    )

neg_pairs = pd.DataFrame(negative_rows)

In [16]:
neg_pairs.head()

            seed_track_id        similar_track_id  target
0  0000vdREvCVMxbQTkS888c  1Mk9ou2m6hsEZJYuNRJFpO       0
1  0000vdREvCVMxbQTkS888c  04amRUbvDaUMmE9U4Vs48E       0
2  0000vdREvCVMxbQTkS888c  6fgmNIMwDdLQrNzu4U8pcU       0
3  0000vdREvCVMxbQTkS888c  4loMxnYbyDG0062VcFrtU5       0
4  0000vdREvCVMxbQTkS888c  0YAqJq4IAInEz4OPnGyBXF       0

### Creating Pairwise Pairs

In [17]:
pairwise_pairs = pd.concat([positive_pairs, neg_pairs], ignore_index=True)

feature_cols = [
    "popularity", "danceability", "energy", "loudness", "speechiness",
    "acousticness", "instrumentalness", "liveness", "valence", "tempo",
    "duration_s",
]

song_features = data.set_index("track_id")[feature_cols]

seed_features = (
    song_features.loc[pairwise_pairs["seed_track_id"]]
    .reset_index(drop=True)
)

candidate_features = (
    song_features.loc[pairwise_pairs["similar_track_id"]]
    .reset_index(drop=True)
)

pairwise_X = seed_features.sub(candidate_features, axis=0).abs()
pairwise_X.columns = [f"{col}_diff" for col in feature_cols]


pairwise_data = pd.concat(
    [pairwise_X, pairwise_pairs[["target"]].reset_index(drop=True)],
    axis=1
)
pairwise_data.head()

,popularity_diff,danceability_diff,energy_diff,loudness_diff,speechiness_diff,acousticness_diff,instrumentalness_diff,liveness_diff,valence_diff,tempo_diff,duration_s_diff,target
0,7.0,0.019,0.190,1.524,0.130,0.0317,0.00301,0.0420,0.059,8.018,2.725,1
1,4.0,0.029,0.092,1.063,0.027,0.0498,0.01159,0.0530,0.281,36.008,41.272,1
2,2.0,0.052,0.222,2.637,0.065,0.0077,0.00300,0.0480,0.273,23.962,57.692,1
3,11.0,0.033,0.135,1.637,0.049,0.0102,0.00301,0.0735,0.147,7.975,23.565,1
4,11.0,0.088,0.049,1.893,0.055,0.2923,0.00301,0.0668,0.046,10.991,23.264,1

In [18]:
lookup = data.set_index("track_id")

pairwise_data_with_ids = pairwise_pairs.copy()

pairwise_data_with_ids["same_genre"] = (
    lookup.loc[pairwise_data_with_ids["seed_track_id"], "track_genre"].values
    ==
    lookup.loc[pairwise_data_with_ids["similar_track_id"], "track_genre"].values
).astype(int)

pairwise_data_with_ids["same_artist"] = (
    lookup.loc[pairwise_data_with_ids["seed_track_id"], "artists"].values
    ==
    lookup.loc[pairwise_data_with_ids["similar_track_id"], "artists"].values
).astype(int)

pairwise_data_with_ids["same_album"] = (
    lookup.loc[pairwise_data_with_ids["seed_track_id"], "album_name"].values
    ==
    lookup.loc[pairwise_data_with_ids["similar_track_id"], "album_name"].values
).astype(int)

pairwise_final = pd.concat(
    [
        pairwise_data_with_ids[["seed_track_id", "similar_track_id"]],
        pairwise_X.reset_index(drop=True),
        pairwise_data_with_ids[["same_genre", "same_artist", "same_album", "target"]].reset_index(drop=True)
    ],
    axis=1
)

pairwise_final.head()

,seed_track_id,similar_track_id,popularity_diff,danceability_diff,energy_diff,loudness_diff,speechiness_diff,acousticness_diff,instrumentalness_diff,liveness_diff,valence_diff,tempo_diff,duration_s_diff,same_genre,same_artist,same_album,target
0,0000vdREvCVMxbQTkS888c,2DX4Lj4wXV3VK1F8yl0x54,7.0,0.019,0.190,1.524,0.130,0.0317,0.00301,0.0420,0.059,8.018,2.725,1,0,0,1
1,0000vdREvCVMxbQTkS888c,4bYH5445Bn2w9UiGM0NxQw,4.0,0.029,0.092,1.063,0.027,0.0498,0.01159,0.0530,0.281,36.008,41.272,1,0,0,1
2,0000vdREvCVMxbQTkS888c,5u7QargOKXO82nXcAU9s8L,2.0,0.052,0.222,2.637,0.065,0.0077,0.00300,0.0480,0.273,23.962,57.692,1,0,0,1
3,0000vdREvCVMxbQTkS888c,0wi1ky0zqwG8195E4omWui,11.0,0.033,0.135,1.637,0.049,0.0102,0.00301,0.0735,0.147,7.975,23.565,0,0,0,1
4,0000vdREvCVMxbQTkS888c,6wKKcAUaLYDy7bN1uFD0E5,11.0,0.088,0.049,1.893,0.055,0.2923,0.00301,0.0668,0.046,10.991,23.264,0,0,0,1

In [19]:
pairwise_final.to_csv("data/pairwise_data.csv", index = False)